version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/theanh28
    steps:
      - checkout # Dowload repo
      - run: yarn install
      - run: yarn run build # build folder dist

      - save_cache:
          paths:
            - node_modules
            - build
            - src/test
            - package.json
            - firebase.json
            - .firebaserc
          key: v1-dependencies-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/theanh28
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 
      - run:
          name: Cháº¡y unit test
          command: yarn test
  deploy:
      docker:
        - image: circleci/node:latest
          environment:
            KEY_TOKEN_FIREBASE: 1//0gwzmGLgHcKb3CgYIARAAGBASNwF-L9IrnELBt5AnWa92ofkhskIbyeYHB8kPHNwZDZkuJ40HAndnNaHU6izFLgz3MXSgmB0HFCI
      working_directory: ~/theanh28 
      steps:
        - restore_cache:
            keys:
              - v1-dependencies-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 
        - run:
            name: show directory 
            command: pwd
        - run: 
            name: show children file
            command: ls
        - run:
            name: Install Firebase
            command: yarn add -D firebase-tools
        - run:
            name: look in directory
            command: ls -ltr
        - run:
            name: Deploy Master to Firebase
            command: yarn deploy-firebase --token=$KEY_TOKEN_FIREBASE
workflows:
  version: 2
  theanh_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master